import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import http from "node:http";
import path from "node:path";

const workspaceFolder = process.env.WORKSPACE_FOLDER ?? process.cwd();
const outputFile = path.join(workspaceFolder, ".devcontainer", "docker-compose.ports.yml");
const dockerSocketPath = process.env.DOCKER_SOCKET_PATH ?? "/var/run/docker.sock";
const probeImage = process.env.PORT_PROBE_IMAGE ?? "node:22-alpine";
const maxPortOffset = Number.parseInt(process.env.PORT_PROBE_MAX_OFFSET ?? "100", 10);

const services = [
  { name: "web", label: "web app", containerPort: 3000, hostPort: 3000 },
  { name: "api", label: "API", containerPort: 8000, hostPort: 8000 },
  { name: "postgres", label: "PostgreSQL", containerPort: 5432, hostPort: 5432 },
  { name: "mongodb", label: "MongoDB", containerPort: 27017, hostPort: 27017 },
  { name: "redis", label: "Redis", containerPort: 6379, hostPort: 6379 },
  { name: "kafka", label: "Kafka", containerPort: 9092, hostPort: 9092 },
];

async function dockerRequest(method, requestPath, body) {
  const payload = body === undefined ? undefined : JSON.stringify(body);

  return await new Promise((resolve, reject) => {
    const request = http.request(
      {
        socketPath: dockerSocketPath,
        path: requestPath,
        method,
        headers: payload
          ? {
              "Content-Type": "application/json",
              "Content-Length": Buffer.byteLength(payload),
            }
          : undefined,
      },
      (response) => {
        let rawBody = "";

        response.setEncoding("utf8");
        response.on("data", (chunk) => {
          rawBody += chunk;
        });
        response.on("end", () => {
          const bodyText = rawBody.trim();
          let parsedBody;

          if (bodyText) {
            try {
              parsedBody = JSON.parse(bodyText);
            } catch {
              parsedBody = bodyText;
            }
          }

          if ((response.statusCode ?? 500) >= 400) {
            const message =
              (typeof parsedBody === "object" ? parsedBody?.message : undefined) ??
              `Docker API ${method} ${requestPath} failed with status ${response.statusCode}.`;
            const error = new Error(message);
            error.statusCode = response.statusCode;
            reject(error);
            return;
          }

          resolve(parsedBody);
        });
      }
    );

    request.on("error", reject);

    if (payload) {
      request.write(payload);
    }

    request.end();
  });
}

async function stopAndRemoveContainer(containerId) {
  try {
    await dockerRequest("POST", `/containers/${containerId}/stop?t=0`);
  } catch (error) {
    if (error.statusCode !== 304 && error.statusCode !== 404) {
      throw error;
    }
  }

  try {
    await dockerRequest("DELETE", `/containers/${containerId}?force=true`);
  } catch (error) {
    if (error.statusCode !== 404) {
      throw error;
    }
  }
}

function isPortConflict(error) {
  const message = `${error.message}`.toLowerCase();
  return (
    message.includes("port is already allocated") ||
    message.includes("address already in use") ||
    message.includes("ports are not available") ||
    message.includes("bind for 0.0.0.0")
  );
}

async function probeHostPort(hostPort) {
  const name = `clubcrm-port-probe-${hostPort}-${randomUUID()}`;
  let containerId;

  try {
    const created = await dockerRequest("POST", `/containers/create?name=${name}`, {
      Image: probeImage,
      Cmd: ["sh", "-c", "sleep 5"],
      ExposedPorts: {
        "80/tcp": {},
      },
      HostConfig: {
        PortBindings: {
          "80/tcp": [{ HostPort: `${hostPort}` }],
        },
      },
    });

    containerId = created.Id;
    await dockerRequest("POST", `/containers/${containerId}/start`);
    return true;
  } catch (error) {
    if (isPortConflict(error)) {
      return false;
    }

    throw error;
  } finally {
    if (containerId) {
      await stopAndRemoveContainer(containerId);
    }
  }
}

async function resolveHostPort(basePort) {
  for (let offset = 0; offset <= maxPortOffset; offset += 1) {
    const candidatePort = basePort + offset;
    if (await probeHostPort(candidatePort)) {
      return candidatePort;
    }
  }

  throw new Error(
    `Unable to find a free host port for ${basePort} within ${maxPortOffset} increments.`
  );
}

function renderComposeOverride(portMappings) {
  const lines = [
    "# Generated by .devcontainer/prepare-ports.mjs",
    "# Do not edit by hand.",
    "services:",
  ];

  for (const mapping of portMappings) {
    lines.push(`  ${mapping.name}:`);
    lines.push("    ports:");
    lines.push(`      - \"${mapping.hostPort}:${mapping.containerPort}\"`);
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

function printSummary(portMappings) {
  console.log("Resolved devcontainer host ports:");

  for (const mapping of portMappings) {
    const suffix =
      mapping.hostPort === mapping.defaultHostPort
        ? `${mapping.hostPort}`
        : `${mapping.defaultHostPort} -> ${mapping.hostPort}`;
    console.log(`- ${mapping.label}: ${suffix}`);
  }
}

async function main() {
  try {
    await dockerRequest("GET", "/_ping");
  } catch (error) {
    throw new Error(`Unable to reach the Docker socket at ${dockerSocketPath}. ${error.message}`);
  }

  const portMappings = [];

  for (const service of services) {
    const resolvedHostPort = await resolveHostPort(service.hostPort);
    portMappings.push({
      ...service,
      defaultHostPort: service.hostPort,
      hostPort: resolvedHostPort,
    });
  }

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, renderComposeOverride(portMappings), "utf8");
  printSummary(portMappings);
}

main().catch((error) => {
  console.error(`Failed to prepare devcontainer host ports: ${error.message}`);
  process.exit(1);
});
