apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clubcrm-web
  namespace: clubcrm
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: clubcrm_route
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.maxage: "43200"
    traefik.ingress.kubernetes.io/service.sticky.cookie.path: /
spec:
  ingressClassName: traefik
  rules:
    - host: clubcrm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clubcrm-web
                port:
                  number: 3000
