apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: clubcrm-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: clubcrm-longhorn
  resources:
    requests:
      storage: 10Gi
