apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clubcrm-api
  namespace: clubcrm
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: clubcrm-strip-api-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: clubcrm.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clubcrm-api
                port:
                  number: 8000
