apiVersion: v1
kind: ConfigMap
metadata:
  name: clubcrm-api-env
  namespace: clubcrm
data:
  API_APP_TITLE: ClubCRM API
  API_HOST: 0.0.0.0
  API_PORT: "8000"
  API_BASE_URL: http://clubcrm-api.clubcrm.svc.cluster.local:8000
  REDIS_URL: redis://redis.clubcrm-data.svc.cluster.local:6379/0
  WEB_API_PUBLIC_BASE_URL: http://clubcrm.local/api
  IS_AUTH_BYPASS: "true"
  AUTH_LOGIN_SUCCESS_URL: http://clubcrm.local/dashboard
  AUTH_LOGOUT_REDIRECT_URL: http://clubcrm.local/login
  AUTH_COOKIE_SECURE: "false"
  AUTH_COOKIE_SAME_SITE: lax
