apiVersion: v1
kind: Secret
metadata:
  name: clubcrm-api-secrets
  namespace: clubcrm
type: Opaque
stringData:
  DATABASE_URL: postgresql://clubcrm:clubcrm@postgres.clubcrm-data.svc.cluster.local:5432/clubcrm
