apiVersion: v1
kind: Service
metadata:
  name: clubcrm-web
  namespace: clubcrm
spec:
  selector:
    app.kubernetes.io/name: clubcrm-web
  ports:
    - name: http
      port: 3000
      targetPort: http
